# Generated by Django 3.0.8 on 2020-12-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20201125_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='logout_url',
            field=models.URLField(default='', help_text='URL to which users will be redirected.', verbose_name='logout URL'),
        ),
    ]
